//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherDesktop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeatherDesktop.Properties.Menu", typeof(Menu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        internal static string APIKey {
            get {
                return ResourceManager.GetString("APIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denied Days.
        /// </summary>
        internal static string DeniedDays {
            get {
                return ResourceManager.GetString("DeniedDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denied Hours.
        /// </summary>
        internal static string DeniedHours {
            get {
                return ResourceManager.GetString("DeniedHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denied Listing.
        /// </summary>
        internal static string DeniedItems {
            get {
                return ResourceManager.GetString("DeniedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        internal static string Global {
            get {
                return ResourceManager.GetString("Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour To Update.
        /// </summary>
        internal static string HourUpdate {
            get {
                return ResourceManager.GetString("HourUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Style.
        /// </summary>
        internal static string IconStyle {
            get {
                return ResourceManager.GetString("IconStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        internal static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Theme.
        /// </summary>
        internal static string ImportTheme {
            get {
                return ResourceManager.GetString("ImportTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Theme.
        /// </summary>
        internal static string LoadTheme {
            get {
                return ResourceManager.GetString("LoadTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Folder.
        /// </summary>
        internal static string PluginFolder {
            get {
                return ResourceManager.GetString("PluginFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As Theme.
        /// </summary>
        internal static string SaveAsTheme {
            get {
                return ResourceManager.GetString("SaveAsTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SunRise/Set.
        /// </summary>
        internal static string SunRiseSet {
            get {
                return ResourceManager.GetString("SunRiseSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        internal static string Themes {
            get {
                return ResourceManager.GetString("Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Interval.
        /// </summary>
        internal static string UpdateInterval {
            get {
                return ResourceManager.GetString("UpdateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ZipCode..
        /// </summary>
        internal static string UpdateZipCode {
            get {
                return ResourceManager.GetString("UpdateZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        internal static string Weather {
            get {
                return ResourceManager.GetString("Weather", resourceCulture);
            }
        }
    }
}
