//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherDesktop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Prompts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Prompts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeatherDesktop.Properties.Prompts", typeof(Prompts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter days in comma seperated values, with Sunday = 0 and Saturday = 6, example &apos;0,1,2&apos; = Sunday Monday Tuesday.
        /// </summary>
        internal static string CSVForDays {
            get {
                return ResourceManager.GetString("CSVForDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter days in comma seperated values, Military time.
        /// </summary>
        internal static string CSVForHours {
            get {
                return ResourceManager.GetString("CSVForHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the API key provided by openweathermap.org.
        /// </summary>
        internal static string EnterAPIKeyFromOpenWeather {
            get {
                return ResourceManager.GetString("EnterAPIKeyFromOpenWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the hour you want to update..
        /// </summary>
        internal static string EnterHourToUpdate {
            get {
                return ResourceManager.GetString("EnterHourToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter New interval between 10 and 120.
        /// </summary>
        internal static string IntervalBetween10and120 {
            get {
                return ResourceManager.GetString("IntervalBetween10and120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter your {0}.
        /// </summary>
        internal static string PleaseEnterYour_ {
            get {
                return ResourceManager.GetString("PleaseEnterYour_", resourceCulture);
            }
        }
    }
}
